repository:
  name: homebrew-solang
  description: Brew tap for Hyperledger Solang
  homepage: https://solang.readthedocs.io/
  topics: brew, solidity, solang
  default_branch: main
  has_downloads: false
  has_issues: true
  has_projects: false
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
